import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const ignored = ["/test/fixtures/", "/node_modules/", "/.git/"];

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = path.join(directory, entry.name);
    const normalized = full.split(path.sep).join("/");
    if (ignored.some((part) => normalized.includes(part))) continue;
    if (entry.isDirectory()) files.push(...(await walk(full)));
    if (entry.isFile() && entry.name === "SKILL.md") files.push(full);
  }
  return files;
}

function frontmatter(source) {
  if (!source.startsWith("---\n")) return {};
  const end = source.indexOf("\n---", 4);
  if (end === -1) return {};
  const block = source.slice(4, end);
  const result = {};
  for (const line of block.split("\n")) {
    const match = line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/);
    if (!match) continue;
    const [, key, raw] = match;
    if (!raw || raw === ">" || raw === "|") continue;
    result[key] = raw.replace(/^["']|["']$/g, "").trim();
  }
  const descriptionMatch = block.match(
    /^description:\s*[>|]\s*\n((?:[ \t]+.*\n?)*)/m,
  );
  if (descriptionMatch) {
    result.description = descriptionMatch[1]
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean)
      .join(" ");
  }
  return result;
}

function collectionFor(relativePath) {
  const community = relativePath.match(/^skills\/community\/([^/]+)/);
  if (community) return community[1];
  if (relativePath.startsWith("skills/personal/")) return "perplexity-user";
  return "uncategorized";
}

function domainFor(name, relativePath, description) {
  const text = `${name} ${relativePath} ${description}`.toLowerCase();
  const rules = [
    ["media", /video|motion|frame|caption|audio|music|slideshow|figma|media/],
    ["travel", /hotel|restaurant|nightlife|bar-selector|travel|destination/],
    ["sports", /footy|soccer|betting|odds|totals/],
    ["marketing", /marketing|seo|cro|copywriting|copy-editing|cold-email|email-sequence|paid-ads|ad-creative|analytics-tracking|churn|referral|lead-magnet|revops|sales-enablement|pricing-strategy|launch-strategy|social-content/],
    ["writing", /writing|document|pdf|slop|editorial|article|resume/],
    ["design", /design|diagram|html|interface|ios/],
    ["engineering", /devex|ios-clean|ios-fix|plan-tune|pair-agent|codex/],
    ["quality-and-release", /review|qa|test|ship|deploy|release|guard|health|freeze|canary|land/],
    ["research-and-browser", /browse|browser|scrape|research|investigate|hackernews/],
    ["strategy-and-product", /office-hours|ceo|plan|spec|benchmark|cso|autoplan/],
    ["orchestration", /context|brain|skill|agent|codex|setup|sync|learn|upgrade|pair/],
  ];
  return rules.find(([, pattern]) => pattern.test(text))?.[0] ?? "orchestration";
}

const files = (await walk(root)).sort();
const skills = [];

for (const file of files) {
  const relativePath = path.relative(root, file).split(path.sep).join("/");
  const source = await readFile(file, "utf8");
  const meta = frontmatter(source);
  const fallbackName = path.basename(path.dirname(file));
  const name = meta.name || fallbackName;
  const description = meta.description || "No manifest description provided.";
  skills.push({
    name,
    description,
    domain: domainFor(name, relativePath, description),
    collection: collectionFor(relativePath),
    path: relativePath,
    version: meta.version || null,
  });
}

skills.sort((a, b) =>
  a.domain.localeCompare(b.domain) || a.name.localeCompare(b.name),
);

const generatedAt = new Date().toISOString();
const catalog = {
  schemaVersion: 1,
  generatedAt,
  count: skills.length,
  skills,
};

await mkdir(path.join(root, "registry"), { recursive: true });
await writeFile(
  path.join(root, "registry/catalog.json"),
  `${JSON.stringify(catalog, null, 2)}\n`,
);

const domains = [...new Set(skills.map((skill) => skill.domain))].sort();
const title = (value) =>
  value
    .split("-")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(" ");

let catalogMarkdown = `# Skill catalog\n\nGenerated from ${skills.length} skill manifests. Do not edit this file directly; run \`npm run catalog\`.\n`;

for (const domain of domains) {
  catalogMarkdown += `\n## ${title(domain)}\n\n`;
  for (const skill of skills.filter((item) => item.domain === domain)) {
    catalogMarkdown += `- [${skill.name}](${skill.path}) · \`${skill.collection}\` — ${skill.description}\n`;
  }
}

await writeFile(path.join(root, "CATALOG.md"), catalogMarkdown);

console.log(`Indexed ${skills.length} skills across ${domains.length} domains.`);
